# Copyright 2020 by the project contributors
# SPDX-License-Identifier: GPL-3.0-only
#
# Author(s): Pavel Benacek <pavel.benacek@gmail.com>

# Select the language
language: bash

# Select the OS to use
os:
    - linux

# Allow docker to run tests inside it
services:
    - docker

# Prepare the docker image in installation stage
install:
    - git clone https://github.com/benycze/bsc-docker-container.git 
    - cd bsc-docker-container && bash bootstrap.sh && docker build -t localhost/bsc-compiler --build-arg BJOBS=2 . && cd ..

script:
    - cd bsv/ && ./start-container.sh -s 

notifications:
  email: false
